'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowUpRight,BarChart3,Check,Download,Gauge,Info,Server,ShieldCheck,Sparkles} from 'lucide-react';
type Inputs={requests:number;inputTokens:number;outputTokens:number;successRate:number;revenuePerSuccess:number;apiInput:number;apiOutput:number;gpuHourly:number;gpuThroughput:number;minimumGpuHours:number;engineering:number;observability:number;egress:number;availability:number;revenueAtRisk:number};
const initial:Inputs={requests:5000000,inputTokens:512,outputTokens:128,successRate:95,revenuePerSuccess:.02,apiInput:.2,apiOutput:.8,gpuHourly:3.4,gpuThroughput:10.8,minimumGpuHours:730,engineering:3500,observability:600,egress:400,availability:99.5,revenueAtRisk:250000};
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const compact=new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1});
function calculate(inputs:Inputs){const mi=inputs.requests*inputs.inputTokens/1e6,mo=inputs.requests*inputs.outputTokens/1e6;const apiCost=mi*inputs.apiInput+mo*inputs.apiOutput;const workloadHours=inputs.requests/Math.max(inputs.gpuThroughput*3600,1);const billedGpuHours=Math.max(workloadHours,inputs.minimumGpuHours);const gpuCompute=billedGpuHours*inputs.gpuHourly;const gpuCost=gpuCompute+inputs.engineering+inputs.observability+inputs.egress;const successes=inputs.requests*inputs.successRate/100;const revenue=successes*inputs.revenuePerSuccess;const outageRisk=inputs.revenueAtRisk*(1-inputs.availability/100);const apiRiskAdjusted=apiCost+outageRisk,gpuRiskAdjusted=gpuCost+outageRisk;const unitApi=(inputs.inputTokens/1e6)*inputs.apiInput+(inputs.outputTokens/1e6)*inputs.apiOutput;return{apiCost,workloadHours,billedGpuHours,gpuCompute,gpuCost,successes,revenue,outageRisk,apiRiskAdjusted,gpuRiskAdjusted,apiCostPerSuccess:apiCost/Math.max(successes,1),gpuCostPerSuccess:gpuCost/Math.max(successes,1),breakEvenRequests:gpuCost/Math.max(unitApi,.00000001)}}
function NumericInput({label,value,suffix,onChange}:{label:string;value:number;suffix?:string;onChange:(v:number)=>void}){return <label className="field"><span>{label}</span><span className="input-wrap"><input aria-label={label} type="number" value={value} min="0" step="any" onChange={e=>onChange(Number(e.target.value))}/>{suffix&&<b>{suffix}</b>}</span></label>}
export default function Home(){
 const [inputs,setInputs]=useState(initial);const [notice,setNotice]=useState('');const update=(key:keyof Inputs)=>(value:number)=>setInputs(c=>({...c,[key]:value}));
 const result=useMemo(()=>calculate(inputs),[inputs]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options?:{signal?:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'calculate_gpu_cloud_cost',title:'Calculate GPU cloud cost',description:'Update the visible calculator with workload and pricing assumptions, then return managed API and self-hosted GPU economics.',inputSchema:{type:'object',properties:Object.fromEntries(Object.keys(initial).map(key=>[key,{type:'number',minimum:0}])),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(raw:unknown){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Input must be an object of numeric calculator fields.');const candidate={...inputs,...raw} as Inputs;for(const [key,value] of Object.entries(raw))if(!(key in initial)||typeof value!=='number'||!Number.isFinite(value)||value<0)throw new Error(`Invalid field: ${key}`);setInputs(candidate);const calculated=calculate(candidate);return{classification:'MODELED_ESTIMATE',recommendation:calculated.apiRiskAdjusted<=calculated.gpuRiskAdjusted?'Managed API':'Self-hosted GPU',managedApiMonthlyUsd:Math.round(calculated.apiRiskAdjusted),selfHostedGpuMonthlyUsd:Math.round(calculated.gpuRiskAdjusted),breakEvenRequests:Math.round(calculated.breakEvenRequests)}}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort()},[inputs]);
 const winner=result.apiRiskAdjusted<=result.gpuRiskAdjusted?'Managed API':'Self-hosted GPU',winnerCost=Math.min(result.apiRiskAdjusted,result.gpuRiskAdjusted),delta=Math.abs(result.apiRiskAdjusted-result.gpuRiskAdjusted),maxCost=Math.max(result.apiRiskAdjusted,result.gpuRiskAdjusted,1);
 function download(){const payload={classification:'MODELED_ESTIMATE',generatedAt:new Date().toISOString(),inputs,result,recommendation:winner,disclaimer:'Replace modeled inputs with contracted prices and measured benchmarks.'};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='gpu-cloud-cost-scenario.json';a.click();URL.revokeObjectURL(url);setNotice('Scenario downloaded');setTimeout(()=>setNotice(''),1800)}
 return <main>
  <header className="topbar"><a className="brand" href="https://a2zsoc.com" target="_blank" rel="noreferrer"><span>A2Z</span> Infrastructure Lab</a><div className="provenance"><i/> Modeled estimate · editable inputs</div><a className="consult" href="https://a2zsoc.com/contact" target="_blank" rel="noreferrer">Request an independent assessment <ArrowUpRight size={15}/></a></header>
  <section className="intro"><div><p className="eyebrow">GPU CLOUD COST CALCULATOR</p><h1>Choose AI infrastructure by <em>successful outcome</em>, not hourly price.</h1></div><p>Compare managed APIs with self-hosted NVIDIA GPU capacity across tokens, utilization, engineering, observability, egress, availability and customer revenue.</p></section>
  <section className="workspace"><aside className="controls"><div className="panel-title"><div><Gauge size={17}/> Workload</div><button onClick={()=>setInputs(initial)}>Reset</button></div><div className="field-grid">
   <NumericInput label="Monthly requests" value={inputs.requests} onChange={update('requests')}/><NumericInput label="Success rate" value={inputs.successRate} suffix="%" onChange={update('successRate')}/><NumericInput label="Input tokens / request" value={inputs.inputTokens} onChange={update('inputTokens')}/><NumericInput label="Output tokens / request" value={inputs.outputTokens} onChange={update('outputTokens')}/><NumericInput label="Revenue / success" value={inputs.revenuePerSuccess} suffix="$" onChange={update('revenuePerSuccess')}/><NumericInput label="Monthly revenue at risk" value={inputs.revenueAtRisk} suffix="$" onChange={update('revenueAtRisk')}/>
  </div><div className="section-label"><Sparkles size={15}/> Managed API</div><div className="field-grid two"><NumericInput label="Input / 1M tokens" value={inputs.apiInput} suffix="$" onChange={update('apiInput')}/><NumericInput label="Output / 1M tokens" value={inputs.apiOutput} suffix="$" onChange={update('apiOutput')}/></div><div className="section-label"><Server size={15}/> Self-hosted GPU</div><div className="field-grid two"><NumericInput label="GPU hourly price" value={inputs.gpuHourly} suffix="$" onChange={update('gpuHourly')}/><NumericInput label="Requests / second" value={inputs.gpuThroughput} onChange={update('gpuThroughput')}/><NumericInput label="Minimum billed hours" value={inputs.minimumGpuHours} suffix="h" onChange={update('minimumGpuHours')}/><NumericInput label="Engineering / month" value={inputs.engineering} suffix="$" onChange={update('engineering')}/><NumericInput label="Observability / month" value={inputs.observability} suffix="$" onChange={update('observability')}/><NumericInput label="Egress / month" value={inputs.egress} suffix="$" onChange={update('egress')}/><NumericInput label="Availability" value={inputs.availability} suffix="%" onChange={update('availability')}/></div></aside>
  <section className="results" aria-live="polite"><div className="recommendation"><div><p>MODELED RECOMMENDATION</p><h2>{winner}</h2><span>{money.format(winnerCost)} risk-adjusted monthly cost</span></div><div className="delta"><small>MODELED DIFFERENCE</small><strong>{money.format(delta)}</strong><span>per month</span></div></div>
  <div className="metrics"><article><span>Successful requests</span><strong>{compact.format(result.successes)}</strong><small>{inputs.successRate}% completion assumption</small></article><article><span>Monthly workflow revenue</span><strong>{money.format(result.revenue)}</strong><small>User-supplied value per success</small></article><article><span>Break-even API volume</span><strong>{compact.format(result.breakEvenRequests)}</strong><small>Requests / month at current inputs</small></article><article><span>Required GPU runtime</span><strong>{compact.format(result.workloadHours)}h</strong><small>{compact.format(result.billedGpuHours)} billed hours</small></article></div>
  <div className="comparison-card"><div className="comparison-head"><div><BarChart3 size={17}/> Monthly comparison</div><span>Risk-adjusted</span></div><div className="bars"><div className="bar-row"><label>Managed API <b>{money.format(result.apiRiskAdjusted)}</b></label><div><i style={{width:`${result.apiRiskAdjusted/maxCost*100}%`}}/></div><small>{money.format(result.apiCostPerSuccess)} / successful request</small></div><div className="bar-row gpu"><label>Self-hosted GPU <b>{money.format(result.gpuRiskAdjusted)}</b></label><div><i style={{width:`${result.gpuRiskAdjusted/maxCost*100}%`}}/></div><small>{money.format(result.gpuCostPerSuccess)} / successful request</small></div></div><div className="cost-grid"><span><small>GPU compute</small><b>{money.format(result.gpuCompute)}</b></span><span><small>Engineering</small><b>{money.format(inputs.engineering)}</b></span><span><small>Observability</small><b>{money.format(inputs.observability)}</b></span><span><small>Egress</small><b>{money.format(inputs.egress)}</b></span><span><small>Expected outage loss</small><b>{money.format(result.outageRisk)}</b></span></div></div>
  <div className="decision-footer"><div><ShieldCheck size={18}/><p><b>Decision boundary</b><span>This estimate excludes model-quality differences, migration, reservations, taxes and contractual capacity guarantees.</span></p></div><button onClick={download}><Download size={16}/> Export scenario</button></div></section></section>
  <section className="methodology"><div><p className="eyebrow">METHOD</p><h2>Every number exposes its assumptions.</h2></div><div className="method-grid"><article><b>01</b><h3>Whole delivery cost</h3><p>Compute, token usage, minimum capacity, engineering, observability and egress are calculated separately.</p></article><article><b>02</b><h3>Successful outcomes</h3><p>Costs are divided by completed workflows—not raw requests or attractive peak-throughput figures.</p></article><article><b>03</b><h3>Risk adjustment</h3><p>Expected availability loss is visible. Production assessments add capacity, supplier and migration risk.</p></article></div></section>
  <section className="cta"><div><p>NEED MEASURED EVIDENCE?</p><h2>Turn this estimate into a defensible capacity and procurement decision.</h2></div><a href="https://a2zsoc.com/contact" target="_blank" rel="noreferrer">Benchmark my workload <ArrowUpRight size={17}/></a></section>
  <footer><span>© 2026 A2Z SOC</span><span><Info size={13}/> No customer inputs are stored.</span><a href="https://github.com/AAH20" target="_blank" rel="noreferrer">Open-source infrastructure research</a></footer>{notice&&<div className="toast"><Check size={15}/> {notice}</div>}
 </main>}
